# Generated by Django 2.2.4 on 2019-09-11 15:32

import converter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FileField(upload_to=converter.models.result_files_upload_path)),
                ('file', models.FileField(upload_to=converter.models.input_files_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConvertedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FileField(upload_to=converter.models.result_files_upload_path)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
